data_sources:
  raw_csv:
    path: "IngresoPromedio.csv"
    encoding: "utf-8"
    delimiter: ","
  
processing:
  date_format: "%Y"
  currency_format: "CLP"
  
validation:
  required_columns:
    - "Indicador"
    - "A침o"
    - "Regi칩n"
    - "Sexo"
    - "Value"
  
  data_types:
    "A침o": "int64"
    "Value": "float64"
    "Sexo": "category"
    "Regi칩n": "category"
    
visualization:
  style:
    name: "economist"
    colors:
      primary: "#1f77b4"
      secondary: "#ff7f0e"
      tertiary: "#2ca02c"
      background: "#f8f9fa"
      text: "#2c3e50"
      accent: "#e74c3c"
    
  fonts:
    title: 
      family: "Arial"
      size: 16
      weight: "bold"
    subtitle:
      family: "Arial"
      size: 12
      weight: "normal"
    axis:
      family: "Arial"
      size: 10
      
  layout:
    margin_left: 0.15
    margin_right: 0.95
    margin_top: 0.85
    margin_bottom: 0.15
